# Generated by Django 3.2 on 2021-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0008_auto_20210623_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='secteur',
            field=models.CharField(max_length=50, verbose_name="Secteur d'Activité"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('SDI', "Stade d'Idée"), ('EGN', 'En Gestation'), ('JLC', 'Juste Lancé'), ('EAE', 'En Activité'), ('C', 'Cloturé')], max_length=30, verbose_name='Statut du Projet'),
        ),
    ]
