# Generated by Django 3.2 on 2021-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deme', '0002_auto_20210623_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financement',
            name='duree',
            field=models.IntegerField(verbose_name='Durée'),
        ),
    ]
